// <auto-generated />
using System;
using ContextServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context_aware_System.Migrations
{
    [DbContext(typeof(ContextAwareDb))]
    [Migration("20231029181359_removeClasses")]
    partial class removeClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.ContextModels.LastVerificationRegist", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComponentProductsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ComponentsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CoordinatorsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DevicesVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LinesVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OperatorsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProductionPlansVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProductionsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProductsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReasonsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Schedule_worker_linesVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StopsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SupervisorsVerification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkersVerification")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("lastVerificationRegists");
                });

            modelBuilder.Entity("Models.ContextModels.Production", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Production_PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("Models.ContextModels.Request", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("Models.ContextModels.Stop", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<bool>("Planned")
                        .HasColumnType("bit");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
